### ISSUE TITLE
Pipeline needs correct fluxscaling! 

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/CASA_eMERLIN_pipeline#1]
Incorporate dfluxpy.py

**Comment by jradcliffe5** [comment]
From amsrichards:

Actually, this reminds me that there is one more gotcha in CASA which I don't have a general workaround for, which is that you cannot use a user-defined model and rescale it by spectral index.  That is (as far as I can remember), you can insert the model but you are stuck with the VLA flux densities and have later to apply the proportional e-MERLIN scaling as defined by Danielle in her dfluxpy code.  That is, at present what I do is to use the resolved model but the VLA flux densities (CASA fluxscale does have some nice options to suppress bad data), derive the other sources' flux densities and then rescale these before using setjy and gaincal (not using the slightly incorrectly directly scaled .fluxscale cal table).  Note that unlike AIPS GETJY, CASA fluxscale does not change the source model flux densities, you have to run setjy.

**Comment by amsrichards** [comment]
Hi,
I have looked at the current CASA capability and this is why it is not possible to use a model at an arbitray C-band frequency without rescaling.  My current pipeline (i.e. for 3C277.1) uses setjy as below.

setjy:
Does not allow model to be uploaded in manual mode.
Using standard            = 'Perley-Butler 2013'
you can upload a model (image clean components, i.e. .model or .model.tt0)
for 1331+305 which is then scaled using the Perley-Butler model (so
there is no need for the .tt1 spec index image)
but it uses the full flux density, hence the need to correct later for
e-MERLIN resolution. 


ft:
Use with 
model               = ['3C286_C.clean.model.tt0', '3C286_C.clean.model.tt1'] #  N
However, this will only fill in where the model supplied overlaps with
the frequencies in the data.  e.g. if the model covers 4.8-5.3 GHz and
the data cover 5.2-5.7 GHz, you only get a model for 5.2-5.3 GHz.

It is all correctly scaled by channel, though!

I will raise/poke some CASA tickets...

**Comment by amsrichards** [comment]
I have commented on CAS-8531 and CAS-4124
for those with access to the CASA JIRA

**Comment by jmoldon** [comment]
Adopted Anita's method using setjy. More details in the pull request #47 and issue #33.
