### ISSUE TITLE
FITS-IDI importer option 

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/CASA_eMERLIN_pipeline#12]
Add and make default a version which uses raw FITS-IDI data from the correlator. Need to fixvis and then check whether doCASAsort is required (for .ms files at least). Should be OK with .mms architecture.

**Comment by jradcliffe5** [comment]
Javier are you currently working on this? I was planning on getting the headless version running +  non-aoflagger dependencies installed today/tomorrow so everyone can use it. Putting in the IDI option too would make sense and I can do it if you arn't working on it atm.

**Comment by jmoldon** [comment]
I don't have the step in the pipeline, although it is straightforward  [ importfitsidi(fitsidifile = infile, vis = msfile) ] . Before preparing any pull request I wanted to have the headless version to properly run "official" tests. Can you include a simple input file that is easy to update by anyone? That way we can check any new feature using only the input file, and when the pull request is accepted you can modify the tk widget accordingly. Sounds good?

**Comment by jradcliffe5** [comment]
Yeah thats fine. So have you modified alot already? Im changing the way the pipeline works at the moment. Because people will directly download the github repository, the pipeline will be in a separate folder. I'm therefore adding data/plots/calibration directory inputs for use in the future. The current version is hardwired to look in the ./ directory. I'll make a simple input file this afternoon which will generate the same dictionaries as inputs.

**Comment by jradcliffe5** [comment]
Done. Will need to modify though once #22 is solved
