### ISSUE TITLE
Investigate use of AOFlagger 2.7 and before

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/CASA_eMERLIN_pipeline#15]
-field option is unavailable in aoflagger v2.7 and earlier so should we split and concat the data or force users to upgrade to v2.8+

**Comment by jmoldon** [comment]
Two different paths implemented:
- For aoflagger <2.9:
     - `ms2mms_fields` (splits in individual MMS per source, and then `virtualconcat`)
     - `run_aoflagger_fields` (executed in the MMS/SUBSS structure)
- For aoflagger 2.9+:
      - `run_aoflagger`
      - `ms2mms`

Finished implementation and testing in #23. Further benchmarking in #28.
