### ISSUE TITLE
Hanning smoothing for mms

### ISSUE THREAD

**Issue by jmoldon** [e-merlin/CASA_eMERLIN_pipeline#17]
Hanning smoothing can also be executed on mms files using mstransform. I use a different order for the initial steps:
- partition (to generate mms)
- mstransform (Hanning smoothing)
- aoflagger

All of those need to be on individual sources (if AOflagger is v2.7) or a combined measurement set (if AOFlagger is v2.9)

**Comment by jradcliffe5** [comment]
Can mstransform do the transform from ms to mms also? I never use it. Would be nice to kill 2 birds with one stone

**Comment by jmoldon** [comment]
I did a quick test and it seems to crash if the mms structure is not present. I have added a condition to check if the filename ends with ms/MS or with mms/MMS and proceed accordingly.

Probably there is a way to check directly looking at the file structure, but this should work for the moment.

**Comment by jmoldon** [comment]
It is implemented in the hanning function. Although we don't need it because we run HS in the MS before converting to MMS
