### ISSUE TITLE
Conflict with casa tasks when loading our libraries

### ISSUE THREAD

**Issue by jmoldon** [e-merlin/CASA_eMERLIN_pipeline#22]
There is a problem with casa accessing its tasks when we try to load our functions with:
`sys.path.insert(0,'./CASA_eMERLIN_pipeline') # add github path at runtime
`
I have seen it with the casa task virtualconcat and I suspect is the same problem Jack had with importfitsidi. When the sys.path is not modified virtualconcat works normally, but when it is modified casa doesn't even recognize the task.

As a temporary solution I have written the task ms2mms_fields, which uses virtualconcat, directly in the pipeline instead on eMERLIN_CASA_functions.py, and then it works.

The solution to this is correctly importing eMERLIN_CASA_functions.py as a submodule instead of a different module linked with sys.path. I still don't know how to do that but it is possible (and recommended) for sure.

**Comment by jradcliffe5** [comment]
Do you think the casa init.py method inclusion will work instead? I will test!

**Comment by jmoldon** [comment]
I have identified two different problems, both easy to solve:
- Yes, it is very simple to implement. I have done a quick test and works fine. We just need to put the different files in a directory that also contains a file __init__.py, which can be empty, and then we can import any submodule. It is explained  [here](http://stackoverflow.com/questions/24302754/python-submodule-imports-using-init-py).

- CASA was not recognizing some tasks (importfitsidi and virtualconcat in particular) when called from eMERLIN_CASA_functions.py. The problem is that, for some dark reason, those tasks come from different parts of casa. The problem is solved simply by loading casa tasks, and doing it in the right order!
```
In: eMERLIN_CASA_function.py
from tasks import *
from casa import *
```

**Comment by jradcliffe5** [comment]
Ugh CASA. Im testing the use of casa's init.py in order to solve the problem. I will commit if it works to your branch and merge #23 as you've solved pt2 of the problem.

**Comment by jradcliffe5** [comment]
Ok it works. Will add example init.py for your ~/.casa folder and remove the task_importfitsidi.py, will commit and merge. Consider this closed.
