### ISSUE TITLE
e-MERLIN models for calibrators

### ISSUE THREAD

**Issue by jradcliffe5** [e-merlin/CASA_eMERLIN_pipeline#25]
Need to get the eMERLIN models (CASA compatible) to be included with the pipeline. @amsrichards do you have these? I only have 3C286 @ C-band which was used for DARA.

**Comment by amsrichards** [comment]
Hi Jack,

The total intensity models as FITS are linked to http://www.e-merlin.ac.uk/data_red/
(the data reduction was done in AIPS so just using importfits in CASA will do).

Actually, this reminds me that there is one more gotcha in CASA which I don't have a general workaround for, which is that you cannot use a user-defined model and rescale it by spectral index.  That is (as far as I can remember), you can insert the model but you are stuck with the VLA flux densities and have later to apply the proportional e-MERLIN scaling as defined by Danielle in her dfluxpy code.  That is, at present what I do is to use the resolved model but the VLA flux densities (CASA fluxscale does have some nice options to suppress bad data), derive the other sources' flux densities and then rescale these before using setjy and gaincal (not using the slightly incorrectly directly scaled .fluxscale cal table).  Note that unlike AIPS GETJY, CASA fluxscale does not change the source model flux densities, you have to run setjy.

This is explained in the original ERIS 3C277.1 script and probably in the DARA one.

If you want the polarization models please let me know, although they are not the cleanest...

I hope that this makes sense,

thanks
a

________________________________

**Comment by jradcliffe5** [comment]
Thanks Anita! 

How does CASA cope with the 3C286 models being an image rather than the CLEAN components you use when you calibrate in AIPS? Surely the calibration artifacts (see file below) get inputted into the model? Is there a way to convert the image or CC table into a CASA model? Otherwise, the best way would be to image the data in CASA in order to create a model minus noise. Could this also solve the issue about fluxscaling from your email? `One could create a 'real' model and rescale it with mstool`

![3c286_l_band](https://cloud.githubusercontent.com/assets/11754064/24650277/fb6dc424-1929-11e7-8654-aef00f486bbc.png)

With regards to the fluxscaling issue, I saw this in the DARA scripts and recently had to do it myself when reducing some e-MERLIN data of some lenses. I think I have this as issue #1 but will add the information from your comment there thanks. Oh and thanks for sending the email out!

**Comment by amsrichards** [comment]
If you look at the scripts, you use FT to put the model image i.e. the CC into the MS (yu can use te imges for nterms >1 if wanted) (sorry, my previous email missed out that step).  So it is no worse than AIPS.

cheers
a


--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards, UK ARC Node, Room 3.136, JBCA, Alan Turing Building,
University of Manchester, M13 9PL +44 (0)161 275 4243
and
MERLIN/VLBI National Facility,  JBO, SK11 9DL, U.K. +44 (0)1477 571321 (tel) 571618 (fax)

________________________________

**Comment by jradcliffe5** [comment]
Sure. But the images that you get from the e-MERLIN website are images with CLEAN components attached. When you import into CASA images you end up with the image rather than the CC components. So when you use task FT you throw in the image + calibration errors whereas in aips you set it to only use the first 1000 CCs. 

In the DARA script, you have a C-band model of the source which is fine i.e.. 

`setjy(vis='all_avg.ms',
          field='1331+305',
          standard='Perley-Butler 2013',
          model='3C286_C.clean.model.tt0')`

Is there an equivalent L-band model?

**Comment by amsrichards** [comment]
d'Oh! sorry, brain wasn't engaged.  Yes i must have CASA images somewhere for L-band.
my apologies
a


--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards, UK ARC Node, Room 3.136, JBCA, Alan Turing Building,
University of Manchester, M13 9PL +44 (0)161 275 4243
and
MERLIN/VLBI National Facility,  JBO, SK11 9DL, U.K. +44 (0)1477 571321 (tel) 571618 (fax)

________________________________

**Comment by amsrichards** [comment]
on almap7, also in /home/amsr/
/raid2/scratch/3C286/CASA/1331+305.clean.image.L.tgz
(tt0 and tt1 - beware, they don't have anything in the file names to indicate that they are L-band)
github won't let me upload a tar archive, sorry.  Please can you either put them somewhere sensible or let me know where you would like them.
thanks

**Comment by jradcliffe5** [comment]
Thanks Anita. I'll grab them and drop them into the main repository. Do you have the C-band ones also?

**Comment by amsrichards** [comment]
d'Oh*2 of course you need the model not the image.  Will do that.  Galloping senility.



--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards, UK ARC Node, Room 3.136, JBCA, Alan Turing Building,
University of Manchester, M13 9PL +44 (0)161 275 4243
and
MERLIN/VLBI National Facility,  JBO, SK11 9DL, U.K. +44 (0)1477 571321 (tel) 571618 (fax)

________________________________

**Comment by amsrichards** [comment]
In /home/amsr

1331+305.clean.C.tgz

1331+305.clean.L.tgz

contain all models (also images etc.)

You might want to just put up the models, on the other hand more experienced users might want to poke in the psf, residuals etc.  and for teaching it is useful to have the image to show the model overlaid.
cheers
a

--------------------------------------------------------------------------------------------------------
Dr. A.M.S. Richards, UK ARC Node, Room 3.136, JBCA, Alan Turing Building,
University of Manchester, M13 9PL +44 (0)161 275 4243
and
MERLIN/VLBI National Facility,  JBO, SK11 9DL, U.K. +44 (0)1477 571321 (tel) 571618 (fax)

________________________________

**Comment by jradcliffe5** [comment]
Fabulous. Thanks Anita. We can put the lot onto the repository.
