### ISSUE TITLE
Clarification: What does mode 0,1,2 mean?

### ISSUE THREAD

**Issue by varenius** [e-merlin/CASA_eMERLIN_pipeline#69]
The following is stated in "inputs.txt":
(0=don't run, 1=run; 2=run and apply calib)

What does this mean for the flagging and averaging tasks? If I run AOflagger with mode 1, will it also apply the flags? If I run averaging with mode 1, will it apply the manual flags before averaging? I'm asking because in AIPS, flag tables can be applied on the fly, but in CASA this behaviour requires work by the flagmanager to appropriately restore flags from preivious steps. I assume all flags are always applied, and the modes are only used in actual calibration tasks. But it would be good to clarify this.

**Comment by jmoldon** [comment]
Value 2 only affects those steps that produce a calibration table. We can add a clarification in the inputs file (and in the docs at some point).

**Comment by jmoldon** [comment]
More clear after b2ae00c739c1482aabd08e3144f43598f1ae784a
