### ISSUE TITLE
Flux scale seems wrong by factor 10 in test obs

### ISSUE THREAD

**Issue by varenius** [e-merlin/CASA_eMERLIN_pipeline#79]
I processed a test observation TSARP220_20171013 C-band through the pipeline 0.6.3 (df2396d) with the following input switches:
Pre-processing (0=don't run, 1=run):
run_importfits  = 1
summary_weblog  = 1
hanning         = 0
ms2mms          = 0
flag_0_aoflagger= 0
flag_1_apriori  = 1
flag_2a_manual  = 1
average_1       = 1
plot_data       = 1
Calibration (0=don't run, 1=run; 2=run and applycal if calibration is produced):
flag_2b_manual  = 2
init_models     = 2
bandpass_0      = 2
flag_3_tfcropBP = 0
delay           = 2
gain_0_p_ap     = 2
fluxscale       = 2
bandpass_1_sp   = 2
gain_1_amp_sp   = 2
applycal_all    = 2
flag_4_rflag    = 0
plot_corrected  = 2
weblog          = 2

The fluxscale.txt-file in the calib directory ends with this summary:
Fitted spectrum for 1516+1932 with fitorder=1: Flux density = 0.065178 +/- 0.000149966
Fitted spectrum for 1407+284 with fitorder=1: Flux density = 0.307479 +/- 0.000785612
Fitted spectrum for 0319+415 with fitorder=1: Flux density = 4.16598 +/- 0.0100069
Fitted spectrum for 1532+2344 with fitorder=1: Flux density = 0.0203492 +/- 5.96974e-05 

On top of my head, what I would have expected is something like 0.6, 3, 0.2 for 1516+1932, 1407+284, 1532+2344. 4Jy for 3C84 seems a bit weak to I think. If all values were ten times higher, I would have accepted them without an extra check. 

Did I make some inconsistent choice of input switches above?

**Comment by jmoldon** [comment]
Yes, those fluxes are not correct. I suspect what is the problem, but can you attach or send the eMCP.log and the casa_eMCP.log files? I think not all those steps were actually executed.

Also, just for efficiency, you don't need to set the values of all the calibration steps to 2 if you are running everything. If you use 2, every step that produces caltables will have to run applycal in CASA just to overwrite once and again the corrected_data column. If you set all those to 1 everything will run the same and the applycal_all will only run at the end to apply all the calibrations. (The value 2 is useful when you want to run one particular step and check what is the effect the calibration up to that step).

**Comment by varenius** [comment]
Here are the log files.
[casa_eMCP.log](https://github.com/e-merlin/CASA_eMERLIN_pipeline/files/1456432/casa_eMCP.log)
[eMCP.log](https://github.com/e-merlin/CASA_eMERLIN_pipeline/files/1456433/eMCP.log)

**Comment by jmoldon** [comment]
The error was that `init_models = 2` does not run the step (it requires a 1). I have updated the inputs file to make it more clear, and now any positive value is accepted. Fixed in eaac7db7f54fb0b17ee9e1b43f6f08edd9012a42
